name: Rebuild README

on:
  pull_request: {}
  push: {}
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install readme-generator
        run: go install gitlab.com/jamietanna/readme-generator@latest

      - name: "Generate README.md"
        run: readme-generator > README.md

      - name: Commit and push (if changed)
        if: github.ref == 'refs/heads/master'
        continue-on-error: true
        run: |-
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add README.md
          git commit -m "Automagic update"
          git push
